###Get all Events
GET http://localhost:3000/events

###Get Event by Id
GET http://localhost:3000/events/67ef644f6235b6f304d4f2a8

###Create Events
POST http://localhost:3000/events HTTP/1.1
Content-Type: application/json

{
    "eventName": "Pet's Fest",
    "eventDescription": "Casual event",
    "date": "2025, April, 10",
    "location":"Xtrem Park",
    "eventStart": "10:00 AM",
    "eventEnd": "02:00 PM",
    "organizerId": "12434",
    "vendorId": "54321"
}

###PUT Events
PUT http://localhost:3000/events/67ef644f6235b6f304d4f2a8 HTTP/1.1
Content-Type: application/json

{
    "eventName": "Claudia's Birthday",
    "eventDescription": "Birthday Party for 10 years old kid x",
    "date": "2019, March, 10",
    "location":"Fantasy Salon",
    "eventStart": "10:00 AM",
    "eventEnd": "02:00 PM",
    "organizerId": "12434",
    "vendorId": "54321"
}

### DELETE Events
DELETE http://localhost:3000/events/
