### Get all accounts
GET http://localhost:3000/tasks


//Soon will be updated
### Get one account (based on id)
GET http://localhost:3000/tasks/


### Create new account
POST http://localhost:3000/tasks/
Content-Type: application/json

{
    "taskName": "Decorations",
    "taskDescription": "Add flowers and balloons to the venue",
    "eventId": "wedding41",
    "organizerId": "565",
    "dueDate": "May 29, 2025",
    "completed": "false"
}

### Update account (based on id)
PUT http://localhost:3000/tasks/67ef70c01bf6ed248d8f5f2f
Content-Type: application/json

{
    "taskName": "Decorations",
    "taskDescription": "Add flowers and balloons to the venue",
    "eventId": "wedding33",
    "organizerId": "565",
    "dueDate": "Apr 09, 2025",
    "completed": "false"
}

### Delete account (based on id)
DELETE http://localhost:3000/tasks/67ef78f644fc173ea750558f
__________________________________________________________________________________________
###Get all Events
GET http://localhost:3000/events

###Get Event by Id
GET http://localhost:3000/events/67f07b591baff3596e42ebfd

###Create Events
POST http://localhost:3000/events HTTP/1.1
Content-Type: application/json

{
    "eventName": "Fashion Fest",
    "eventDescription": "Casual event",
    "date": "2026, April, 10",
    "location":"Fashion mall",
    "eventStart": "6:00 PM",
    "eventEnd": "10:00 PM",
    "organizerId": "12434",
    "vendorId": "54321"
}

###PUT Events
PUT http://localhost:3000/events/67f0cfac1ee033c2dac590bd HTTP/1.1
Content-Type: application/json

{
    "eventName": "Claudia's Birthday",
    "eventDescription": "Birthday Party for 10 years old kid x",
    "date": "2019, March, 10",
    "location":"Fantasy Salon",
    "eventStart": "10:00 AM",
    "eventEnd": "02:00 PM",
    "organizerId": "12434",
    "vendorId": "54321"
}

### DELETE Events
DELETE http://localhost:3000/events/67f0cfac1ee033c2dac590bd


### Get all accounts
GET http://localhost:3000/location


//Soon will be updated
### Get one account (based on id)
GET http://localhost:3000/location/


### Create new account
POST http://localhost:3000/location/
Content-Type: application/json

{
    "locationName": "Fashion Mall",
    "locationDescription": "Fashion mall in the city center",
    "lattitude": 40.7128,
    "longitude": -74.0060,
    "address": "123 Fashion St, Cityville",
    "city": "Cityville",
    "country": "Countryland",

}

###PUT Events
PUT http://localhost:3000/location/ HTTP/1.1
Content-Type: application/json

{
    "locationName": "Wedding Venue",
    "locationDescription": "Beautiful garden for weddings",
    "lattitude": 80.0028,
    "longitude": -34.0060,
    "address": "123 Fashion St, Cityville",
    "city": "ville",
    "country": "estate",
}

### DELETE Events
DELETE http://localhost:3000/location/